version: '3.9'

services:
  manager-db:
    image: postgres:14.13-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - manager-school

  pgadmin:

    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - manager-db
    networks:
      - manager-school

  manager-school-app:
    container_name: manager-school
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=manager-db
      - DB_PORT=5432
      - DB_NAME=postgres
    depends_on:
      - manager-db
    networks:
      - manager-school

volumes:
  postgres_data:

networks:
  manager-school:
    driver: bridge
